### PR TITLE
Update version.json

### PR DESCRIPTION
**Pull request by ST-Apps**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/PoGo-Devs/PoGo/pull/38" target="_blank">ReviewNinja

**Comment by SmailSmailko** [comment]
добрий вечір))
коли буде змога заходити в програму?77))
дякую

**Comment by swisszeni** [comment]
Write in english. And stop commenting unrelated topics to a PR.

**Comment by SmailSmailko** [comment]
Sorry
and when will the renewal because the program can not go
thanks for understanding

**Comment by UPseppeGG** [comment]
Hi, how this patch can solve actual situation: Obsolete version ? or is only a step up and we have to wait a new version of Pogo UWP ?

**Comment by UPseppeGG** [comment]
I'm only a user. Can i help otherwise ?

**Pull request merged**
